import type { SiteContent } from "@/lib/types";

/**
 * Local content. The site renders from this whenever Supabase env vars
 * are missing, so `npm run dev` works on a fresh clone with zero setup.
 * Once Supabase is wired up, rows there win and this becomes the safety net.
 *
 * Projects were pulled from github.com/Tejastarle (24 own repos, 1 fork skipped).
 */

export const fallbackContent: SiteContent = {
  projects: [
    {
      id: "p-merkmetryx",
      slug: "merkmetryx",
      title: "Merkmetryx",
      tagline:
        "Market-research and analytics platform. Three payment gateways normalised behind one gateway-agnostic interface, with a survey ingestion pipeline and automated executive reporting.",
      body:
        "Architected and built the complete backend: REST APIs, authentication, role-based access, a survey data ingestion pipeline and automated report generation.\n\nIntegrated three payment gateways — Razorpay, Stripe and PayPal — through direct API integration, covering order creation, checkout handoff, signature and webhook verification, refunds, and reconciliation of pending and failed transactions.\n\nNormalised three different provider response formats behind a single internal payment interface so the application layer stays gateway-agnostic. Delivered interactive data visualisation and executive reporting used for business insight.",
      category: "enterprise",
      stack: ["ReactJS", "Node.js", "Express", "MongoDB", "Razorpay", "Stripe", "PayPal"],
      repo_url: null,
      live_url: null,
      cover_url: null,
      language: "TypeScript",
      featured: true,
      year: 2026,
      sort_order: 0,
      published: true,
      updated_at: "2026-08-20",
    },
    {
      id: "p-ecokart",
      slug: "ecokart",
      title: "EcoKart",
      tagline:
        "Full-stack e-commerce platform. Idempotent order handling and webhook-driven payment status updates keep charges and order state in sync.",
      body:
        "Built the backend end to end: product catalogue, cart and order services, user authentication, and checkout with integrated payment processing.\n\nImplemented idempotent order handling and webhook-driven payment status updates to prevent duplicate charges and stale order state. Designed the order state machine (created, paid, fulfilled, refunded) so payment events and order status never drift out of sync.",
      category: "web",
      stack: ["ReactJS", "Node.js", "Express", "MongoDB", "Payments"],
      repo_url: "https://github.com/Tejastarle/EcoKart",
      live_url: null,
      cover_url: null,
      language: "TypeScript",
      featured: true,
      year: 2026,
      sort_order: 1,
      published: true,
      updated_at: "2026-08-14",
    },
    {
      id: "p-apex-crm",
      slug: "apex-crm",
      title: "Apex CRM",
      tagline:
        "Freelance CRM backend delivered end to end — lead pipeline, customer records, role-based dashboards and activity-tracking APIs.",
      body:
        "Designed and developed the full backend: lead pipeline, customer records, role-based dashboards and activity tracking APIs.\n\nDelivered independently end to end, from requirements and schema design through API build, deployment and client handover.",
      category: "enterprise",
      stack: ["Node.js", "Express", "MongoDB", "REST"],
      repo_url: "https://github.com/Tejastarle/Apex-CRM",
      live_url: null,
      cover_url: null,
      language: "JavaScript",
      featured: true,
      year: 2026,
      sort_order: 2,
      published: true,
      updated_at: "2026-08-07",
    },
    {
      id: "p-doortodoor",
      slug: "doortodoor-marketing",
      title: "DoorToDoor Marketing",
      tagline: "Field-campaign tracking and lead capture.",
      body: null,
      category: "enterprise",
      stack: ["TypeScript", "React"],
      repo_url: "https://github.com/Tejastarle/doortodoor-marketing",
      live_url: null,
      cover_url: null,
      language: "TypeScript",
      featured: true,
      year: 2026,
      sort_order: 3,
      published: true,
      updated_at: "2026-08-14",
    },
    {
      id: "p-daddus",
      slug: "daddus-biryani",
      title: "Daddus Biryani",
      tagline: "Restaurant ordering site, menu to checkout.",
      body: null,
      category: "web",
      stack: ["TypeScript", "React"],
      repo_url: "https://github.com/Tejastarle/daddus-biryani-complete",
      live_url: null,
      cover_url: null,
      language: "TypeScript",
      featured: true,
      year: 2026,
      sort_order: 4,
      published: true,
      updated_at: "2026-08-06",
    },
    {
      id: "p-womensafety",
      slug: "women-safety-app",
      title: "Women Safety App",
      tagline: "Real-time safety app with SOS alerting and live GPS tracking. Published in IJARIIE, Volume 11, 2025.",
      body:
        "Real-time safety application with SOS alerting, live GPS tracking and emergency response coordination, backed by Firebase Realtime Database for instant sync.\n\nPublished as research in the International Journal IJARIIE, Volume 11, 2025.",
      category: "android",
      stack: ["Java", "Firebase", "GPS"],
      repo_url: "https://github.com/Tejastarle/WomenSafetyApp",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: true,
      year: 2025,
      sort_order: 5,
      published: true,
      updated_at: "2025-01-30",
    },
    {
      id: "p-sparkwomen",
      slug: "sparkwomen",
      title: "SparkWomen",
      tagline: "Emergency-response companion app.",
      body: null,
      category: "android",
      stack: ["Java", "Firebase"],
      repo_url: "https://github.com/Tejastarle/SparkWomen",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: true,
      year: 2025,
      sort_order: 6,
      published: true,
      updated_at: "2025-04-11",
    },
    {
      id: "p-smartcity",
      slug: "smart-city",
      title: "Smart City",
      tagline: "Civic services and reporting interface.",
      body: null,
      category: "web",
      stack: ["HTML", "CSS", "JavaScript"],
      repo_url: "https://github.com/Tejastarle/smart-city",
      live_url: null,
      cover_url: null,
      language: "HTML",
      featured: false,
      year: 2026,
      sort_order: 7,
      published: true,
      updated_at: "2026-04-21",
    },
    {
      id: "p-projectmgmt",
      slug: "project-management",
      title: "Project Management",
      tagline: "Sprint boards, task assignment, delivery tracking.",
      body: null,
      category: "enterprise",
      stack: ["JavaScript", "Node.js"],
      repo_url: "https://github.com/Tejastarle/Project_Management-master",
      live_url: null,
      cover_url: null,
      language: "JavaScript",
      featured: true,
      year: 2025,
      sort_order: 8,
      published: true,
      updated_at: "2025-09-30",
    },
    {
      id: "p-plantbio",
      slug: "plantbio-dictionary",
      title: "PlantBio Dictionary",
      tagline: "Plant identification and reference platform.",
      body: null,
      category: "android",
      stack: ["Java", "Android"],
      repo_url: "https://github.com/Tejastarle/PlantBioDictionary",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: false,
      year: 2025,
      sort_order: 9,
      published: true,
      updated_at: "2025-02-12",
    },
    {
      id: "p-baoiamapp",
      slug: "baoiam-app",
      title: "Baoiam App",
      tagline: "Learning app built with Jetpack Compose.",
      body: null,
      category: "android",
      stack: ["Kotlin", "Jetpack Compose"],
      repo_url: "https://github.com/Tejastarle/BaoiamApp",
      live_url: null,
      cover_url: null,
      language: "Kotlin",
      featured: false,
      year: 2024,
      sort_order: 10,
      published: true,
      updated_at: "2024-09-04",
    },
    {
      id: "p-baoiam-official",
      slug: "baoiam-official",
      title: "Baoiam Official",
      tagline: "Cross-platform client build in Flutter.",
      body: null,
      category: "android",
      stack: ["Dart", "Flutter"],
      repo_url: "https://github.com/Tejastarle/Baoiam_Official-main",
      live_url: null,
      cover_url: null,
      language: "Dart",
      featured: false,
      year: 2024,
      sort_order: 11,
      published: true,
      updated_at: "2024-08-28",
    },
    {
      id: "p-infinity",
      slug: "infinity",
      title: "Infinity",
      tagline: "Motion-led marketing site.",
      body: null,
      category: "web",
      stack: ["CSS", "JavaScript"],
      repo_url: "https://github.com/Tejastarle/infinity-",
      live_url: null,
      cover_url: null,
      language: "CSS",
      featured: false,
      year: 2025,
      sort_order: 12,
      published: true,
      updated_at: "2025-12-29",
    },
    {
      id: "p-expenditure",
      slug: "expenditure-app",
      title: "Expenditure App",
      tagline: "Personal spend tracking on Android.",
      body: null,
      category: "android",
      stack: ["Java", "SQLite"],
      repo_url: "https://github.com/Tejastarle/expenditure_app",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: false,
      year: 2024,
      sort_order: 13,
      published: true,
      updated_at: "2024-08-28",
    },
    {
      id: "p-notes",
      slug: "notes-taker",
      title: "Notes Taker",
      tagline: "Offline-first note capture.",
      body: null,
      category: "android",
      stack: ["Java", "Room"],
      repo_url: "https://github.com/Tejastarle/NOTES_TAKER_1",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: false,
      year: 2024,
      sort_order: 14,
      published: true,
      updated_at: "2024-08-28",
    },
    {
      id: "p-appdrawer",
      slug: "app-drawer",
      title: "App Drawer",
      tagline: "Intent passing and navigation patterns reference.",
      body: null,
      category: "android",
      stack: ["Java", "Android"],
      repo_url: "https://github.com/Tejastarle/app_drawer",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: false,
      year: 2025,
      sort_order: 15,
      published: true,
      updated_at: "2025-01-22",
    },
    {
      id: "p-todolist",
      slug: "todolist-app",
      title: "ToDoList App",
      tagline: "Task manager with persistent storage.",
      body: null,
      category: "android",
      stack: ["Java", "Android"],
      repo_url: "https://github.com/Tejastarle/ToDoList_App",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: false,
      year: 2024,
      sort_order: 16,
      published: true,
      updated_at: "2024-08-28",
    },
    {
      id: "p-oldaccessories",
      slug: "old-accessories-drawer",
      title: "Old Accessories Drawer",
      tagline: "Resale listings marketplace.",
      body: null,
      category: "web",
      stack: ["JavaScript"],
      repo_url: "https://github.com/Tejastarle/Old_Accessories_Drawer",
      live_url: null,
      cover_url: null,
      language: "JavaScript",
      featured: false,
      year: 2024,
      sort_order: 17,
      published: true,
      updated_at: "2024-09-04",
    },
    {
      id: "p-loginpage",
      slug: "my-loginpage",
      title: "Login Page",
      tagline: "Auth screen with validation states.",
      body: null,
      category: "android",
      stack: ["Java", "Android"],
      repo_url: "https://github.com/Tejastarle/my_loginpage",
      live_url: null,
      cover_url: null,
      language: "Java",
      featured: false,
      year: 2025,
      sort_order: 18,
      published: true,
      updated_at: "2025-01-13",
    },
  ],

  experience: [
    {
      id: "e-agix",
      role: "Vice President & Program Manager",
      company: "Agix International Pvt. Ltd.",
      location: "Remote, India",
      employment_type: "Full-Time",
      start_date: "2025-12-01",
      end_date: null,
      highlights: [
        "Build and ship backend services for the Agix corporate platform and internal tooling in Node.js, Express and MongoDB — REST API design, authentication, role-based access control and deployment pipelines.",
        "Translate ambiguous business requirements into concrete API contracts and technical specifications across ReactJS, Node.js, Firebase, Flutter and LLM tooling.",
        "Build market-research dashboards, analytics platforms and automated reporting services used for executive decision-making.",
        "Own the delivery lifecycle for 15+ enterprise and SME clients: scoping, architecture, sprint planning, release and sign-off; maintain 95% on-time delivery with no escalation leakage.",
        "Introduce CI/CD pipelines and SOP documentation, cutting manual release and handover effort by roughly 30%.",
      ],
      sort_order: 1,
    },
    {
      id: "e-apex-infinity",
      role: "Full-Stack Developer & Team Lead",
      company: "Apex Infinity Tech",
      location: "Nashik, India",
      employment_type: "Full-Time",
      start_date: "2025-05-01",
      end_date: "2025-12-01",
      highlights: [
        "Joined as a full-stack intern and was promoted to corporate trainer, then team leader, within 90 days.",
        "Delivered five live client projects as the primary developer — React front ends, Node.js and Express APIs, and MongoDB data models.",
        "Led a small delivery team through code review, sprint stand-ups and performance reviews; team KPI achievement improved 40% over the period.",
        "Designed and ran internal training on engineering communication, code quality and client negotiation for 30+ associates.",
      ],
      sort_order: 2,
    },
    {
      id: "e-lokare",
      role: "Android Development Trainer",
      company: "Lokare's Infotech",
      location: "India",
      employment_type: "Part-Time",
      start_date: "2024-11-01",
      end_date: "2025-03-01",
      highlights: [
        "Taught 200+ students across multiple batches in Android fundamentals, app architecture and Play Store deployment using Java, XML and Android Studio.",
        "Ran debugging sessions and walked students through production release workflows.",
      ],
      sort_order: 3,
    },
    {
      id: "e-baoiam",
      role: "Android Developer Intern & Development Lead",
      company: "Baoiam Innovations",
      location: "India",
      employment_type: "Internship",
      start_date: "2024-07-01",
      end_date: "2024-10-01",
      highlights: [
        "Development lead on a production Android application; designed and implemented every component end to end, from screen architecture to backend API contracts.",
        "Owned the full payment gateway integration (Razorpay and Stripe): checkout flow, server-side order creation, signature verification, callback handling and failure/retry logic.",
        "Implemented OAuth and OTP authentication including token refresh and session management.",
        "Integrated Firebase Realtime Database and Cloud Messaging for live data sync, push notifications and in-app analytics.",
        "Rebuilt the UI to Material Design standards, reducing reported UX defects by 25%.",
      ],
      sort_order: 4,
    },
    {
      id: "e-faith",
      role: "Web Developer Intern & Team Lead",
      company: "Faith Group",
      location: "India",
      employment_type: "Internship",
      start_date: "2023-11-01",
      end_date: "2024-03-01",
      highlights: [
        "Primary developer across multiple client projects, building and maintaining full-stack web and mobile applications end to end.",
        "Configured and operated 10+ live client websites: hosting, DNS and domain setup, server provisioning, SSL, and production deployments on Linux with post-launch debugging.",
      ],
      sort_order: 5,
    },
  ],

  certifications: [
    {
      id: "c-oracle",
      name: "Oracle Certified Foundations Associate",
      issuer: "Oracle",
      year: 2024,
      credential_url: null,
      sort_order: 1,
    },
    {
      id: "c-cognizant",
      name: "Cognizant AI Job Simulation",
      issuer: "Cognizant / Forage",
      year: 2024,
      credential_url: null,
      sort_order: 2,
    },
    {
      id: "c-aicte",
      name: "AICTE Android Developer Internship Certification",
      issuer: "AICTE",
      year: 2024,
      credential_url: null,
      sort_order: 3,
    },
    {
      id: "c-tata",
      name: "TATA Data Visualisation Program",
      issuer: "Tata Group / Forage",
      year: 2024,
      credential_url: null,
      sort_order: 4,
    },
    {
      id: "c-tcs",
      name: "TCS iON Business Communication Skills",
      issuer: "TCS iON",
      year: 2023,
      credential_url: null,
      sort_order: 5,
    },
  ],

  posts: [
    {
      id: "b-1",
      slug: "shipping-as-a-program-manager",
      title: "What changed when I stopped writing all the code",
      excerpt:
        "Moving from developer to program manager did not make the work less technical. It made the failure modes different.",
      body: "Write this one in the admin panel. This placeholder exists so the blog route renders on a fresh clone.",
      cover_url: null,
      tags: ["delivery", "leadership"],
      published: true,
      published_at: "2026-06-01",
    },
  ],
};
